name: build-and-test

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build-and-test:
    if: ${{ github.event_name != 'push' || github.ref_name == github.event.repository.default_branch }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        include:
          - rosdistro: humble
            container: nvidia/cuda:12.2.0-devel-ubuntu22.04
            build-depends-repos: build_depends.repos
    steps:
      - name: Setup ROS
        run: |
          echo 'Etc/UTC' > /etc/timezone && \
              ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
              apt-get update && \
              apt-get install -q -y --no-install-recommends tzdata && \
              rm -rf /var/lib/apt/lists/*
          apt-get update && apt-get install -q -y --no-install-recommends \
              dirmngr \
              gnupg2 \
              && rm -rf /var/lib/apt/lists/*
          echo "deb http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2-latest.list
          apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
          DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
              ros-humble-perception \
              && rm -rf /var/lib/apt/lists/*
          source /opt/ros/humble/setup.bash
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Upload coverage to CodeCov
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.test.outputs.coverage-report-files }}
          fail_ci_if_error: false
          verbose: true
          flags: total
